on:
  workflow_dispatch:
jobs:
  read_static_secret:
    permissions:
      contents: read
      id-token: write
    name: Example of reading a static secret
    runs-on: ubuntu-latest

    steps:
    - name: Read Secrets
      uses: hashicorp/vault-action@v2
      with:
        # The URL for the vault endpoint
        url: ${{ secrets.VAULT_ADDR }}
        namespace: admin  
        method: jwt
        role: github_jwt
        # path: # optional
        jwtGithubAudience: sigstore # set the GitHub token's aud claim

        
        # Whether or not export secrets as environment variables.
        exportEnv: true # optional, default is true
        # A semicolon-separated list of secrets to retrieve. These will automatically be converted to environmental variable keys. See README for more details
        secrets: |
          secret/data/ci/aws accessKey | AWS_ACCESS_KEY_ID ;
          secret/data/ci/aws secretKey | AWS_SECRET_ACCESS_KEY ;
          secret/data/ci npm_token
        
        # Time in seconds, after which token expires
        #jwtTtl: # optional, default is 3600
        # The encoding type of the secret to decode. If not specified, the secret will not be decoded. Supported values: base64, hex, utf8
        #secretEncodingType: # optional

  read_dynamic_secret:
    name: Example of reading a dynamic secret
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write
