on:
  workflow_dispatch:
jobs:
  read_static_secret:
    permissions:
      contents: read
      id-token: write
    name: Example of reading a static secret
    runs-on: ubuntu-latest

    steps:
    - name: Read Static Secrets
      id: secrets
      uses: hashicorp/vault-action@v2
      with:
        # The URL for the vault endpoint
        url: ${{ vars.VAULT_ADDR }}
        tlsSkipVerify: true
        namespace: ${{ vars.VAULT_NAMESPACE }}
        method: jwt
        role: example_role
        path: github_jwt # optional
        jwtGithubAudience: example_audience # set the GitHub token's aud claim

        
        # Whether or not export secrets as environment variables.
        exportEnv: true # optional, default is true

        # Whether or not export Vault token as environment variables (i.e VAULT_TOKEN).
        exportToken: true # optional, default is true

        # A semicolon-separated list of secrets to retrieve. These will automatically be converted to environmental variable keys. See README for more details
        secrets: |
          secret/data/sample-secret first-secret | FIRST_SECRET ;
        
        # Time in seconds, after which token expires
        #jwtTtl: # optional, default is 3600
        # The encoding type of the secret to decode. If not specified, the secret will not be decoded. Supported values: base64, hex, utf8
        #secretEncodingType: # optional
    - name: output of reading a static secret
      run: |
        echo "static secret: $(echo ${FIRST_SECRET} | base64)"

    - name: Revoke token
      if: always()
      run: |
        curl -X POST -k -sv -H "X-Vault-Namespace: ${{ vars.VAULT_NAMESPACE }}" -H "X-Vault-Token: ${VAULT_TOKEN}" ${{ vars.VAULT_ADDR }}/v1/auth/token/revoke-self 
